update unrz script

diff --git a/bash/unrz b/bash/unrz
--- a/bash/unrz
+++ b/bash/unrz
@@ -17,100 +17,152 @@ shopt -s extglob
 shopt -s nocaseglob
 
 base_dir="$PWD"
+delete_files=true
+
+create_replacement=true
+replacement_message="replaced by unrz"
 
 #
 # Todo
-# - use file command to get verify the filetype
+# - use file command to verify the filetype
 # - more and better error messages
 #
 
-for file in "$@"; do
-    case $file in
-        *zip)
-            target_dir="${file%\.zip}"
-            ext_cmd="unzip"
-            ;;
-        *rar)
-            target_dir="${file%\.rar}"
-            ext_cmd="unrar x"
-            ;;
-        *bz2)
-            target_dir="${file%\.bz2}"
-            ext_cmd="tar xjf"
-            ;;
-        *tar.gz)
-            target_dir="${file%\.tar\.gz}"
-            ext_cmd="tar xzf"
-            ;;
-        *.tar)
-            target_dir="${file%\.tar}"
-            ext_cmd="tar xf"
-            ;;
-        *.gz)
-            target_dir="${file%\.gz}"
-            ext_cmd="gunzip"
-            ;;
-        *)
-            echo "unknown format"
+unrz_file(){
+    local content
+    local verbose=false
+    for file in "$@"; do
+        cd "$base_dir"
+
+        #skip non files
+        [[ -f "$file" ]] || continue
+
+        #skip files that have already been replaced
+        read -n $((${#replacement_message}*3)) content <"$file"
+        if [[ "$content" == "$replacement_message" ]]; then
+            $verbose && echo "skipping file: '$file' already unpacked";
             continue
-            ;;
-    esac
+        fi
 
-    [[ -f "$file" ]] || continue
-    ext="${file##*\.}"
+        # filter for known formats
+        case $file in
+            *zip)
+                local target_dir="${file%\.zip}"
+                local ext_cmd="unzip"
+                ;;
+            *rar)
+                local target_dir="${file%\.rar}"
+                local ext_cmd="unrar x"
+                ;;
+            *bz2)
+                local target_dir="${file%\.bz2}"
+                local ext_cmd="tar xjf"
+                ;;
+            *tar.gz)
+                local target_dir="${file%\.tar\.gz}"
+                local ext_cmd="tar xzf"
+                ;;
+            *.tar)
+                local target_dir="${file%\.tar}"
+                local ext_cmd="tar xf"
+                ;;
+            *.gz)
+                local target_dir="${file%\.gz}"
+                local ext_cmd="gunzip"
+                ;;
+            *.xz)
+                local target_dir="${file%\.xz}"
+                local ext_cmd="tar xf"
+                ;;
+            *.deb)
+                local target_dir="${file%\.deb}"
+                local ext_cmd="ar x"
+                ;;
+            *)
+                echo "unknown format $file"
+                continue
+                ;;
+        esac
 
-    multipart=false
-    re=".+(P|p)(A|a)(R|r)(T|t)[0-9]+\\.$ext"
-    if [[ $file =~ $re ]]; then
-        echo "found multipart $ext"
-        multipart=true
-        #prefix is target dir
-        target_dir="${file%\.part*\.$ext}"
-    fi
+        #get extention
+        local ext="${file##*\.}"
+        #get filename without path
+        local filename="${file##*/}"
 
-    echo "taget: $target_dir"
+        #check for multipart files
+        local multipart=false
+        local re=".+(P|p)(A|a)(R|r)(T|t)[0-9]+\\.$ext"
+        if [[ $file =~ $re ]]; then
+            echo "found multipart $ext"
+            local multipart=true
+            #prefix is target dir
+            local target_dir="${file%\.part*\.$ext}"
+        fi
 
-    mkdir "$target_dir" || continue
 
-    if $multipart; then
-        mv_fail=false
-        part_list=()
-        for part in "$target_dir"*"$ext"; do
-            if [[ -f "$part" ]]; then
-                mv "$part" "$target_dir" || { mv_fail=true; continue; }
-                part_list+=( "$part" )
-            fi
-        done
-        $mv_fail && continue
-    else
-        mv "$file" "$target_dir" || continue
-        part_list=( "$file" )
-    fi
+        #create target dir -- is realtive
+        if ! mkdir "$target_dir"; then
+            target_dir="$target_dir-possilbe_dupe"
+            mkdir "$target_dir" || continue
+        fi
 
-    cd "$target_dir" || continue
-    $ext_cmd "$file" || continue
+        echo "taget: $target_dir"
 
-    rm_fail=false
-    for part in "${part_list[@]}"; do
-        rm "$part" || rm_fail=true
-    done
-    $rm_fail && continue
+        local part_list=()
+        local mv_fail=false
+        if $multipart; then # unpack multipart
+            #move all parts to new dir
+            for part in "$target_dir"*"$ext"; do
+                if [[ -f "$part" ]]; then
+                    mv "$part" "$target_dir" || { mv_fail=true; continue; }
+                    part_list+=( "$target_dir/$filename" )
+                    $create_replacement && echo "$replacement_message" > "$part"
+                fi
+            done
+            $mv_fail && continue
+        else
+            mv "$file" "$target_dir" || continue
+            local part_list=( "$target_dir/$filename" )
+            set +x
+            $create_replacement && echo "$replacement_message" > "$file"
+        fi
 
-    file_list=(*)
+        #create subshell
+        (
 
-    if [[ ${#file_list[@]} -eq 1 ]]; then
-        ext_dir="${file_list[0]}"
-        if [[ -d "$ext_dir" ]]; then
-            if [[ "$ext_dir" == "$target_dir" ]]; then
-                mv "${file_list[0]}"/* . || continue
-                rm -fr "${file_list[0]}"
-            else
-                mv "$ext_dir" "$base_dir" || continue
-                cd "$base_dir" || continue
-                rm -fr "$target_dir"
+        cd "$target_dir" || continue
+        $ext_cmd "${filename}" 1>/dev/null || continue
+
+        local rm_fail=false
+        if $delete_files; then
+            cd "$base_dir"
+            for part in "${part_list[@]}"; do
+                rm "$part" || { rm_fail=true && echo "failed to delete $part"; }
+            done
+        fi
+        $rm_fail && continue
+
+        exit
+
+        local file_list=(*)
+
+        if [[ ${#file_list[@]} -eq 1 ]]; then
+            local ext_dir="${file_list[0]}"
+            if [[ -d "$ext_dir" ]]; then
+                if [[ "$ext_dir" == "$target_dir" ]]; then
+                    mv "${file_list[0]}"/* . || continue
+                    rm -fr "${file_list[0]}"
+                else
+                    mv "$ext_dir" "$base_dir" || continue
+                    cd "$base_dir" || continue
+                    rm -fr "$target_dir"
+                fi
             fi
         fi
-    fi
 
-    cd "$base_dir"
-done
+        cd "$base_dir"
+        )
+    done
+}
+
+unrz_file "$@"
